# Proteomics Longitudinal Analysis on the UKB.

## Load Packages

## Load data

In [1]:
#Load modules
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re

In [2]:
#mount google drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

###Olink proteomics
*This table contains protein expression info of the different participants, each columns means a protein*

In [3]:
#Olink_proteomics

olink_proteomics_df = pd.read_csv("/content/drive/Shareddrives/UKB_Data/Raw_data/Copia de olink_data.tsv", sep="\t")
olink_proteomics_df.head()

,eid,f_183801_0,f_183802_0,f_183803_0,f_183804_0,f_183805_0,f_183806_0,f_183807_0,f_183808_0,f_183809_0,...,f_183802798_3,f_183802805_3,f_183802807_3,f_183802808_3,f_183802811_3,f_183802813_3,f_183802815_3,f_183802825_3,f_183802834_3,f_183802839_3
0,1000428,-0.4161,-0.34175,0.45155,0.0372,0.4493,0.9716,1.6605,0.2928,0.6318,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1000733,-0.2114,0.08865,0.19445,-0.3721,-0.2925,-0.2254,-1.6076,0.0739,-0.2268,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1000786,0.3317,0.52155,0.36340,0.0541,0.3679,0.5792,-0.5366,0.3326,0.3272,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1000952,0.6352,0.20735,1.08470,0.1064,0.9497,1.8300,0.2250,1.8695,1.2220,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1001279,0.0081,-0.62070,-0.02600,0.5784,0.2625,0.5433,-1.7003,0.3429,1.4269,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Olink Chars

*This table contains info about columns of the olink table values*

In [4]:
#Olink Chars

# Leer el archivo original, saltando las primeras 5 líneas
with open('/content/drive/Shareddrives/UKB_Data/Raw_data/Copia de olink_chars.tsv', 'r') as f:
    lines = f.readlines()[5:]



# Guardar el resultado en un nuevo archivo
with open('/content/drive/Shareddrives/UKB_Data/Proteomics_modified_data/olink_chars_table.tsv', 'w') as f:
    f.writelines(lines)

In [5]:
olink_proteomics_chars_df = pd.read_csv("/content/drive/Shareddrives/UKB_Data/Proteomics_modified_data/olink_chars_table.tsv", sep="\t")

#Crear columna con el nombre de las proteinas y #ordenar df
cols = olink_proteomics_chars_df.columns.tolist()
olink_proteomics_chars_df.insert(cols.index("ValueType"), "pname",olink_proteomics_chars_df["Field"].str.split(";").str[0])
olink_proteomics_chars_df.head()

,Field,FieldID,pname,ValueType,Coding,Category,Participants,Items,Stability,Units,ItemType,Strata,Sexed,Instances,Array,Notes,Link,Path
0,A1BG;Alpha-1B-glycoprotein,183801,A1BG,float,NaN,1838,NaN,NaN,Complete,NaN,Data,Primary,Unisex,0,1,A1BG;Alpha-1B-glycoprotein: a1bg: Protein meas...,http://biobank.ndph.ox.ac.uk/ukb/field.cgi?id=...,Biological samples > Blood assays > Proteomics...
1,AAMDC;Mth938 domain-containing protein,183802,AAMDC,float,NaN,1838,NaN,NaN,Complete,NaN,Data,Primary,Unisex,0,1,AAMDC;Mth938 domain-containing protein: aamdc:...,http://biobank.ndph.ox.ac.uk/ukb/field.cgi?id=...,Biological samples > Blood assays > Proteomics...
2,AARSD1;Alanyl-tRNA editing protein Aarsd1,183803,AARSD1,float,NaN,1838,NaN,NaN,Complete,NaN,Data,Primary,Unisex,3,1,AARSD1;Alanyl-tRNA editing protein Aarsd1: aar...,http://biobank.ndph.ox.ac.uk/ukb/field.cgi?id=...,Biological samples > Blood assays > Proteomics...
3,ABCA2;ATP-binding cassette sub-family A member 2,183804,ABCA2,float,NaN,1838,NaN,NaN,Complete,NaN,Data,Primary,Unisex,0,1,ABCA2;ATP-binding cassette sub-family A member...,http://biobank.ndph.ox.ac.uk/ukb/field.cgi?id=...,Biological samples > Blood assays > Proteomics...
4,ABHD14B;Protein ABHD14B,183805,ABHD14B,float,NaN,1838,NaN,NaN,Complete,NaN,Data,Primary,Unisex,3,1,ABHD14B;Protein ABHD14B: abhd14b: Protein meas...,http://biobank.ndph.ox.ac.uk/ukb/field.cgi?id=...,Biological samples > Blood assays > Proteomics...

###Phenotypes
*This table contains info about habits*

In [1]:
phenotypes_df = pd.read_csv("/content/drive/Shareddrives/UKB_Data/Raw_data/Copia de phenotype_data.tsv", sep="\t")
phenotypes_df.head()

NameError: name 'pd' is not defined

###Etnicity
*This table contains Etnicity info of the different participants according to the genetics. is coded in a PCA base*

In [ ]:
etnicidad_df = pd.read_csv("/content/drive/Shareddrives/UKB_Data/Raw_data/Copia de genomics_data.tsv", sep="\t")
etnicidad_df.head()

,eid,f_22000_0_0,f_22001_0_0,f_22003_0_0,f_22004_0_0,f_22005_0_0,f_22006_0_0,f_22009_0_1,f_22009_0_2,f_22009_0_3,...,f_22024_0_0,f_22025_0_0,f_22026_0_0,f_22027_0_0,f_22028_0_0,f_22029_0_0,f_22030_0_0,f_22007_0_0,f_22008_0_0,f_22182_0_0
0,1000012,10.0,0.0,0.186874,0.188240,0.008535,1.0,-12.4522,2.97502,-1.526670,...,44.7400,99.059,0.97000,NaN,1.0,1.0,1.0,SMP4_0010894A,G03,"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,..."
1,1000021,-7.0,1.0,0.190092,0.191694,0.001877,1.0,-13.8955,6.01974,-2.011150,...,93.3443,99.477,0.95280,NaN,1.0,1.0,1.0,SMP4_0008357,B08,"0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,..."
2,1000035,-2.0,0.0,0.190206,0.191802,0.001883,1.0,-11.7626,4.23129,-3.091340,...,30.1373,99.595,0.96018,NaN,1.0,1.0,1.0,SMP4_0008467,C11,"1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,..."
3,1000044,57.0,1.0,0.190249,0.191653,0.003119,1.0,-11.2151,4.37638,0.766213,...,29.3400,99.580,0.98000,NaN,1.0,1.0,1.0,SMP4_0011008A,A03,"0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,..."
4,1000053,69.0,0.0,0.190025,0.191251,0.002626,1.0,-10.4144,2.19996,0.545220,...,22.1800,99.572,0.97000,NaN,1.0,1.0,1.0,SMP4_0013058A,H12,"0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,..."

### Physical Measures
*This table contains clinical info of the different participants, such as Weight, Height, Artritis, Pregnancy etc*

In [ ]:
physical_measures_df = pd.read_csv("/content/drive/Shareddrives/UKB_Data/Raw_data/Copia de Physical_measures_data.tsv", sep="\t")
physical_measures_df.head()

<ipython-input-9-4304e2814123>:1: DtypeWarning: Columns (248) have mixed types. Specify dtype option on import or set low_memory=False.
  physical_measures_df = pd.read_csv("/content/drive/Shareddrives/UKB_Data/Raw_data/Copia de Physical_measures_data.tsv", sep="\t")

,eid,f_21_0_0,f_21_1_0,f_21_2_0,f_21_3_0,f_36_0_0,f_36_1_0,f_36_2_0,f_36_3_0,f_37_0_0,...,f_23128_3_0,f_23129_0_0,f_23129_1_0,f_23129_2_0,f_23129_3_0,f_23130_0_0,f_23130_1_0,f_23130_2_0,f_23130_3_0,f_39_0_0
0,1000012,1.0,NaN,NaN,NaN,3782.0,NaN,NaN,NaN,NaN,...,NaN,18.7,NaN,NaN,NaN,17.9,NaN,NaN,NaN,2872.0
1,1000021,1.0,NaN,NaN,NaN,3780.0,NaN,NaN,NaN,NaN,...,NaN,37.9,NaN,NaN,NaN,36.5,NaN,NaN,NaN,2872.0
2,1000035,1.0,NaN,NaN,NaN,163.0,NaN,NaN,NaN,NaN,...,NaN,22.5,NaN,NaN,NaN,21.5,NaN,NaN,NaN,2882.0
3,1000044,1.0,3.0,NaN,NaN,3780.0,1046.0,NaN,NaN,NaN,...,NaN,44.0,NaN,NaN,NaN,42.3,NaN,NaN,NaN,2898.0
4,1000053,1.0,NaN,NaN,NaN,1058.0,NaN,NaN,NaN,NaN,...,NaN,25.3,NaN,NaN,NaN,24.2,NaN,NaN,NaN,2889.0

### First Ocurrences
*This table says info about the differents diseases along the DB*

In [ ]:
first_occurences_df = pd.read_csv("/content/drive/Shareddrives/UKB_Data/Raw_data/Copia de FirstOccurrences_data.tsv", sep="\t")
first_ocurrences_df.head()

NameError: name 'pd' is not defined

##Pre Proccess

In [6]:
#Encuentra columnas duplicadas y eliminalas
olink_proteomics_df = olink_proteomics_df.loc[:, ~olink_proteomics_df.columns.duplicated()]

In [7]:
##Cambiar las columnas de Olink_proteomics, pasarlas de formato: FieldID_instance a formato: Nombre_instancia

# Extraer columnas (excepto 'eid')
original_cols = olink_proteomics_df.columns.tolist()
data_cols = original_cols[1:]

# Extraer FieldID y instance de los nombres de columna
fids = [int(re.search(r'f_(\d+)_', col).group(1)) if re.search(r'f_(\d+)_', col) else None for col in data_cols]
instances = [re.sub(r'f_\d+_|f_NA_', '', col) for col in data_cols]

# Crear DataFrame auxiliar
col_df = pd.DataFrame({'old': data_cols, 'fids': fids, 'instance': instances})

# Unir con olinkchar para obtener los 'pname'
col_df = col_df.merge(olink_proteomics_chars_df[['FieldID', 'pname']], left_on='fids', right_on='FieldID', how='left')

# Crear nuevos nombres
col_df['newname'] = col_df['pname'] + '_' + col_df['instance']

# Asignar nuevos nombres de columna
olink_proteomics_df.columns = ['eid'] + col_df['newname'].tolist()

# Obtener la columna 'eid'
eids = olink_proteomics_df['eid']

In [8]:
olink_proteomics_df.head()

,eid,A1BG_0,AAMDC_0,AARSD1_0,ABCA2_0,ABHD14B_0,ABL1_0,ABO_0,ABRAXAS2_0,ACAA1_0,...,TST_3,TXLNA_3,TXNDC15_3,TXNDC5_3,TXNRD1_3,TYRO3_3,UBAC1_3,UMOD_3,USO1_3,UXS1_3
0,1000428,-0.4161,-0.34175,0.45155,0.0372,0.4493,0.9716,1.6605,0.2928,0.6318,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1000733,-0.2114,0.08865,0.19445,-0.3721,-0.2925,-0.2254,-1.6076,0.0739,-0.2268,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1000786,0.3317,0.52155,0.36340,0.0541,0.3679,0.5792,-0.5366,0.3326,0.3272,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1000952,0.6352,0.20735,1.08470,0.1064,0.9497,1.8300,0.2250,1.8695,1.2220,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1001279,0.0081,-0.62070,-0.02600,0.5784,0.2625,0.5433,-1.7003,0.3429,1.4269,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
# Convert column names to strings
olink_proteomics_df.columns = olink_proteomics_df.columns.astype(str)

# Hay proteinas que no estan en las 4 sets longitudinales, por lo que se tiene que decidir o tener en cuenta!!!
# Ejemplo:
filtered_columns = [col for col in olink_proteomics_df.columns if col.startswith('CD6')]
print(filtered_columns)

['CD6_0', 'CD63_0', 'CD69_0', 'CD6_2', 'CD63_2', 'CD69_2', 'CD6_3', 'CD63_3', 'CD69_3']

In [30]:
##Phenotypes DF ####
##¿Cuales fenotipos estan mas associados a la condicion de tener ibd?
#Se sabe por bibliografia que: smoking y alcohol

phenotypes_df.head()
phenodata_esential_df = phenotypes_df.iloc.filter(regex=r'_20116_|_20117_', axis=1)
phenodata_esential_df.head()
"""
# Renombrar las columnas
phenodata_esential.columns = phenodata_esential.columns \
    .str.replace('f_20116', 'Smoking') \
    .str.replace('f_20117', 'Alcohol') \
    .str.replace('_0$', '', regex=True)

# Mostrar el DataFrame con las nuevas columnas
print(phenodata_esential.head())"""

NameError: name 'phenotypes_df' is not defined